### PR TITLE
migrate to Settings DSL

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
and of course the CI is broken due to the Puppet split…

**Comment by evgeni** [comment]
@ares would love some help here, this is the last plugin still using non-DSL settings, and while I think I have the DSL part right in this PR, CI doesn't work and I really don't feel comfortable merging it as-is.

**Comment by to-kn** [comment]
@ares @evgeni any eta for a merge on this?

**Review by ares — APPROVED** [review]
Untested, but does what other plugins did and I don't see anything goofy. Merging, since it can't make it worse than it is now.

Thanks @evgeni, merging

**Comment by ares** [comment]
FTR: tests are broken but it does not look related, import_facts method does not seem to be defined where expected

**Pull request merged**
