### PR TITLE
Rewrite/cleanup for 1.12

### PR DESCRIPTION
**Pull request by GregSutcliffe**
A few commits here. Firstly I've added Rubocop - making that pass led to a refactoring of the core module, so then I rewrote all the tests too. The tests are much more sane, and makes it much easiesr to spot issues and add new features.

I've also updated much of the style to match the current version of the template plugin, where possible. There are areas not updated but it's not essential, just nice-to-have

Finally, fixes are included for #17 and #20 - this makes it locked to 1.12 or greater, so the requirements are updated to match. #20 also requires that we now patch Host::Base rather than Host::Managed, so the files are renamed accordingly.

Tests appear to pass on my branch (http://ci.theforeman.org/view/Plugins/job/test_plugin_matrix/1601) and my local testing appears to work, but it's a big patch - even if the new functionality is small. If someone could review, that would be great, and I'll bump the version and package for 1.12 once it's in.

### CODE REVIEW

**Comment by davividal** [comment]
I have a fresh install of 1.12 RC3.
I have a /usr/share/foreman/bundler.d/Gemfile.local.rb with the following content:

```
# cat /usr/share/foreman/bundler.d/Gemfile.local.rb
gem 'foreman_default_hostgroup', :git => "https://github.com/GregSutcliffe/foreman_default_hostgroup.git", :branch => 'rewrite'
```

But I have no Gemfile nor Gemfile.lock, just Gemfile.in .
I tried to build this gem, but there is no Rakefile.

How can I install this branch?

**Comment by sh41** [comment]
https://theforeman.org/plugins/#2.3AdvancedInstallationfromGems may be able to help. For example on Debian you would:

```
su - foreman
bundle update foreman_default_hostgroup
```

and then restart foreman

hth

**Comment by davividal** [comment]
I already tried that:

```
-bash-4.2$ pwd
/usr/share/foreman
-bash-4.2$ bundle update foreman_default_hostgroup
Could not locate Gemfile
$ ls -a /usr/share/foreman
.  ..  app  bin  bundler.d  config  config.ru  db  extras  Gemfile.in  lib  locale  log  migrate  plugins  public  Rakefile  script  seeds.d  seeds.rb  .ssh  tmp  VERSION
```

What am I missing?
I installed 1.12 RC3 using foreman-installer.

**Comment by GregSutcliffe** [comment]
@davividal I'm assuming you're on a RH-based distro rather than a Debian one - it's very difficult to update non-packaged gems there. I'm not seeing any issues though, so I'll do a release this week I think. Stay tuned :)

**Comment by dLobatog** [comment]
Basic functionality checking-in a host puts it in the right hostgroup , both via regex or specifying the name directly, so :+1:

**Pull request merged**
