### PR TITLE
Applying @ReneCamu patches

### PR DESCRIPTION
**Pull request by davividal**
Issue related: https://github.com/theforeman/foreman_default_hostgroup/issues/18

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Thanks! Any chance you could could add tests? You might want to wait until #22 is merged (or rebase on top) as I've rewritten the tests - should only be a day or so ;)

**Comment by davividal** [comment]
@GregSutcliffe I won't be able to look into this until next week. But it is on my todo list.

**Comment by superfantasticawesome** [comment]
This is a very important feature that will markedly improve functionality. Is this PR going to succeed?

**Comment by GregSutcliffe** [comment]
@superfantasticawesome If I didn't want it, I'd close it :)

This PR had stalled because there's no tests - @davividal mentioned he might have time to look at it, but not right away - and since then it's dropped off my radar. So, in reality, as soon as someone (maybe even me) has time to sit down and add some tests, it can probably be merged and released.

**Comment by ares** [comment]
I appologize, this plugin has not been maintained for a long time. Given the tests were not provided, I'm closing for now. I'll try to find an active maintainer, please consider reopening if tests are added.

**Pull request closed without merging**
