### PR TITLE
Update to default_hostgroup_base_host_patch.rb

### PR DESCRIPTION
**Pull request by dasmall80**
Possible fix for alias_method_chain to prepend for Foreman 1.17 compatibility.
Update import_facts to include source_proxy parameter to avoid argument errors.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Works for me, just need to run the test cases. Thanks @dasmall80!

**Comment by Sebor** [comment]
I can confirm it works for me too

**Comment by GregSutcliffe** [comment]
Included in #37 where I've "fixed" the tests, but I had to do evil things. Almost there!

**Comment by GregSutcliffe** [comment]
#37 is merged, thanks again @dasmall80!

**Pull request closed without merging**
